#配置es的集群名称，默认是elasticsearch，es会自动发现在同一网段下的es，如果在同一网段下有多个集群，就可以用这个属性来区分不同的集群。
cluster:
  name: searchelastics

node:
  #节点名，默认随机指定一个name列表中名字，该列表在es的jar包中config文件夹里name.txt文件中，其中有很多作者添加的有趣名字。
  name: 'node1'
  #指定该节点是否有资格被选举成为node，默认是true，es是默认集群中的第一台机器为master，如果这台机挂了就会重新选举master。
  master: true
  #指定该节点是否存储索引数据，默认为true。
  data: true

index:
  #设置默认索引分片个数，默认为5片。
  numberOfShards: 2
  #设置默认索引副本个数，默认为1个副本。
  numberOfReplicas: 1

path:
  #设置索引数据的存储路径，默认是es根目录下的data文件夹，可以设置多个存储路径，用逗号隔开，例： path.data: /path/to/data1,/path/to/data2
  data: D:/searchelastics/node1/data
  #设置临时文件的存储路径，默认是es根目录下的work文件夹。
  work: D:/searchelastics/node1/work
  #设置日志文件的存储路径，默认是es根目录下的logs文件夹
  logs: D:/searchelastics/node1/logs
  #设置插件的存放路径，默认是es根目录下的plugins文件夹
  plugins: D:/searchelastics/node1/plugins

network:
  #设置绑定的ip地址，可以是ipv4或ipv6的，默认为0.0.0.0。
  bindHost: 192.168.0.1
  #设置其它节点和该节点交互的ip地址，如果不设置它会自动判断，值必须是个真实的ip地址。
  publishHost: 192.168.0.1
  #这个参数是用来同时设置bind_host和publish_host上面两个参数。
  host: 0.0.0.0

tcp:
  #设置节点间交互的tcp端口，默认是9300。
  port: 9201
  #设置是否压缩tcp传输时的数据，默认为false，不压缩。
  compress: true

http:
  #设置对外服务的http端口，默认为9200。
  port: 9200
  #设置内容的最大容量，默认100mb
  maxContentLengthMb: 100
  #是否使用http协议对外提供服务，默认为true，开启。
  enabled: false

gateway:
  #gateway的类型，默认为local即为本地文件系统，可以设置为本地文件系统，分布式文件系统，hadoop的#HDFS，和amazon的s3服务器，其它文件系统的设置方法下次再详细说。
  type: local
  #设置集群中N个节点启动时进行数据恢复，默认为1。
  recoverAfterNodes: 1
  #设置初始化数据恢复进程的超时时间，默认是5分钟。
  recoverAfterTime: 5
  #设置这个集群中节点的数量，默认为2，一旦这N个节点启动，就会立即进行数据恢复。
  expectedNodes: 2

recovery:
  #初始化数据恢复时，并发恢复线程的个数，默认为4
  nodeInitialPrimariesRecoveries: 4
  # 设置数据恢复时限制的带宽，如入100mb，默认为0，即无限制。
  maxSizePerSec: 100
  #设置数据恢复时限制的带宽，如入100mb，默认为0，即无限制。
  concurrentStreams: 5

zk:
  url: 106.53.83.52:2181
  sessionTimeout: 30
  connectionTimeout: 15
  namespace: SE
  retryNum: 3
  retryDelayMs: 1000
